# Generated by Django 3.2.4 on 2021-06-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
    ]
